# -*- coding: utf-8 -*-
"""Grooming

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wa_3pgR-pqsj6vrWQhF41oM8ubBAH9Er

# ФИО
"""

print("Номер Группы: 20БИ-3")
print("Фамилия: Ланских")
print("Имя: Юлия")
print("Отчество: Дмитриевна")
!ln -fs /usr/share/zoneinfo/Europe/Moscow /etc/localtime
!date

"""# Соединение с гугл-диском"""

!pip install --upgrade gspread
import gspread
from google.colab import drive
drive.mount('/content/drive')
import os
print(os.getcwd())
print(os.listdir('./'))
print(os.listdir('/content/drive'))
print(os.listdir('/content/drive/MyDrive/Colab Notebooks/ex2_table'))

"""# Strengths -- столбчатая диаграмма"""

# Commented out IPython magic to ensure Python compatibility.

import os
import time
from google.colab import auth
auth.authenticate_user()
!pip install --upgrade gspread

import gspread
from oauth2client.client import GoogleCredentials
print('\nРаботаем с таблицей')
# %ll -lAF /content/drive/MyDrive/"Colab Notebooks"/ex2_table/
gs = gspread.authorize(GoogleCredentials.get_application_default())
os.stat('/content/drive/MyDrive/Colab Notebooks/ex2_table/grooming1.gsheet')
table = gs.open_by_key('1vadY3Rfap6x2k2GG-_SRWftGApEWWBqyUflBOW5SejU')
print(dir(table))
worksheet = table.worksheet('strength')  
rows = worksheet.get_all_values()
k = [0.0] * 4
text = ['fff'] * 4
f = 0
for i in rows:
  if i[4] != '' and i[4] != 'powers':
    text[f] = i[0]
    k[f] = float(i[4])
    print(k[f])
    print(text[f])
    f = f+1 


import matplotlib.pyplot as plt
x=list()
x_float=list()
title=list()
y_float=list()
title = [text[0], text[1], text[2], text[3]]
x=title
x_float = [1, 2, 3, 4]
y = [k[0], k[1],k[2],k[3]]
y_float = [k[0], k[1], k[2], k[3]]
print(x_float,title,y_float)
print('списки формированы-->\n')
x_pos=list()
for i in range(x_float.__len__()):
    x_pos.append(i)
print('<!--разбивка по абсцисс и значения ординат\n', len( x_float), x_pos, y_float, ' -->\n')
fig=plt.figure(figsize=(8,6), dpi=72)
plt.bar(x_pos, y_float, width=0.75, align='edge', alpha=0.4)
plt.xticks(x_pos,  x_float, fontsize=14)
plt.xlabel('Обозначения1', fontsize=14)
plt.ylabel('Мощность воздействия', fontsize=14)
plt.title('STRENGTHS', fontsize=14)
plt.grid(True, color='r', linestyle='-', linewidth=2)
#plt.draw()
plt.show()
fig.savefig("/content/drive/MyDrive/Colab Notebooks/ex2_table/strength_bar.png")
print('<div class="d-flex flex-row ">')
print('<div class="card m-1" style="width: 28rem;">',
      '<img  src="/content/drive/MyDrive/Colab Notebooks/ex2_table/strength_bar.png" class="card-img-top" alt="...">',
      '<div class="card-body">')
    
for i in range(title.__len__()):
    print(i+1, " - ", title[i], "; ")
    i += 1
print('</div>', '</div>')
print('<div>')

"""# Weakness -- cтолбчатая диаграмма """

# Commented out IPython magic to ensure Python compatibility.

import os
import time
from google.colab import auth
auth.authenticate_user()
!pip install --upgrade gspread

import gspread
from oauth2client.client import GoogleCredentials
print('\nРаботаем с таблицей')
# %ll -lAF /content/drive/MyDrive/"Colab Notebooks"/ex2_table/
gs = gspread.authorize(GoogleCredentials.get_application_default())
os.stat('/content/drive/MyDrive/Colab Notebooks/ex2_table/grooming1.gsheet')
table = gs.open_by_key('1vadY3Rfap6x2k2GG-_SRWftGApEWWBqyUflBOW5SejU')
print(dir(table))
worksheet = table.worksheet('weakness')  
rows = worksheet.get_all_values()
k = [0.0] * 4
text = ['fff'] * 4
f = 0
for i in rows:
  if i[4] != '' and i[4] != 'powers':
    text[f] = i[0]
    k[f] = float(i[4])
    print(k[f])
    print(text[f])
    f = f+1 

import matplotlib.pyplot as plt
x=list()
x_float=list()
title=list()
y_float=list()
title = [text[0], text[1], text[2], text[3]]

x=title
x_float = [1, 2, 3, 4]
y = [k[0], k[1],k[2],k[3]]
y_float = [k[0], k[1], k[2], k[3]]
print(x_float,title,y_float)
print('списки формированы-->\n')
x_pos=list()
for i in range(x_float.__len__()):
    x_pos.append(i)
print('<!--разбивка по абсцисс и значения ординат\n', len( x_float), x_pos, y_float, ' -->\n')
fig=plt.figure(figsize=(8,6), dpi=72)
plt.bar(x_pos, y_float, width=0.75, align='edge', alpha=0.4)
plt.xticks(x_pos,  x_float, fontsize=14)
plt.xlabel('Обозначения1', fontsize=14)
plt.ylabel('Мощность воздействия', fontsize=14)
plt.title('WEAKNESSES', fontsize=14)
plt.grid(True, color='r', linestyle='-', linewidth=2)
#plt.draw()
plt.show()
fig.savefig("/content/drive/MyDrive/Colab Notebooks/ex2_table/weakness_bar.png")
print('<div class="d-flex flex-row ">')
print('<div class="card m-1" style="width: 28rem;">',
      '<img  src="/content/drive/MyDrive/Colab Notebooks/ex2_table/weakness_bar.png" class="card-img-top" alt="...">',
      '<div class="card-body">')
    
for i in range(title.__len__()):
    print(i+1, " - ", title[i], "; ")
    i += 1
print('</div>', '</div>')
print('<div>')

"""# Opportunities -- cтолбчатая диаграмма """

# Commented out IPython magic to ensure Python compatibility.

import os
import time
from google.colab import auth
auth.authenticate_user()
!pip install --upgrade gspread

import gspread
from oauth2client.client import GoogleCredentials
print('\nРаботаем с таблицей')
# %ll -lAF /content/drive/MyDrive/"Colab Notebooks"/ex2_table/
gs = gspread.authorize(GoogleCredentials.get_application_default())
os.stat('/content/drive/MyDrive/Colab Notebooks/ex2_table/grooming1.gsheet')
table = gs.open_by_key('1vadY3Rfap6x2k2GG-_SRWftGApEWWBqyUflBOW5SejU')
print(dir(table))
worksheet = table.worksheet('opportunities')  
rows = worksheet.get_all_values()
k = [0.0] * 4
text = ['fff'] * 4
f = 0
for i in rows:
  if i[4] != '' and i[4] != 'powers':
    text[f] = i[0]
    k[f] = float(i[4])
    print(k[f])
    print(text[f])
    f = f+1 

import matplotlib.pyplot as plt
x=list()
x_float=list()
title=list()
y_float=list()
title = [text[0], text[1], text[2], text[3]]
x=title
x_float = [1, 2, 3, 4]
y = [k[0], k[1],k[2],k[3]]
y_float = [k[0], k[1], k[2], k[3]]
print(x_float,title,y_float)
print('списки формированы-->\n')
x_pos=list()
for i in range(x_float.__len__()):
    x_pos.append(i)
print('<!--разбивка по абсцисс и значения ординат\n', len( x_float), x_pos, y_float, ' -->\n')
fig=plt.figure(figsize=(8,6), dpi=72)
plt.bar(x_pos, y_float, width=0.75, align='edge', alpha=0.4)
plt.xticks(x_pos,  x_float, fontsize=14)
plt.xlabel('Обозначения1', fontsize=14)
plt.ylabel('Мощность воздействия', fontsize=14)
plt.title('OPPORTUNITIES', fontsize=14)
plt.grid(True, color='r', linestyle='-', linewidth=2)
#plt.draw()
plt.show()
fig.savefig("/content/drive/MyDrive/Colab Notebooks/ex2_table/opportunities_bar.png")
print('<div class="d-flex flex-row ">')
print('<div class="card m-1" style="width: 28rem;">',
      '<img  src="/content/drive/MyDrive/Colab Notebooks/ex2_table/opportunities_bar.png" class="card-img-top" alt="...">',
      '<div class="card-body">')
    
for i in range(title.__len__()):
    print(i+1, " - ", title[i], "; ")
    i += 1
print('</div>', '</div>')
print('<div>')

"""# Threats -- cтолбчатая диаграмма """

# Commented out IPython magic to ensure Python compatibility.

import os
import time
from google.colab import auth
auth.authenticate_user()
!pip install --upgrade gspread

import gspread
from oauth2client.client import GoogleCredentials
print('\nРаботаем с таблицей')
# %ll -lAF /content/drive/MyDrive/"Colab Notebooks"/ex2_table/
gs = gspread.authorize(GoogleCredentials.get_application_default())
os.stat('/content/drive/MyDrive/Colab Notebooks/ex2_table/grooming1.gsheet')
table = gs.open_by_key('1vadY3Rfap6x2k2GG-_SRWftGApEWWBqyUflBOW5SejUU')
print(dir(table))
worksheet = table.worksheet('threats')  
rows = worksheet.get_all_values()
k = [0.0] * 4
text = ['fff'] * 4
f = 0
for i in rows:
  if i[4] != '' and i[4] != 'powers':
    text[f] = i[0]
    k[f] = float(i[4])
    print(k[f])
    print(text[f])
    f = f+1 

import matplotlib.pyplot as plt
x=list()
x_float=list()
title=list()
y_float=list()
title = [text[0], text[1], text[2], text[3]]
x=title
x_float = [1, 2, 3, 4]
y = [k[0], k[1],k[2],k[3]]
y_float = [k[0], k[1], k[2], k[3]]
print(x_float,title,y_float)
print('списки формированы-->\n')
x_pos=list()
for i in range(x_float.__len__()):
    x_pos.append(i)
print('<!--разбивка по абсцисс и значения ординат\n', len( x_float), x_pos, y_float, ' -->\n')
fig=plt.figure(figsize=(8,6), dpi=72)
plt.bar(x_pos, y_float, width=0.75, align='edge', alpha=0.4)
plt.xticks(x_pos,  x_float, fontsize=14)
plt.xlabel('Обозначения1', fontsize=14)
plt.ylabel('Мощность воздействия', fontsize=14)
plt.title('THREATS', fontsize=14)
plt.grid(True, color='r', linestyle='-', linewidth=2)
#plt.draw()
plt.show()
fig.savefig("/content/drive/MyDrive/Colab Notebooks/ex2_table/threats_bar.png")
print('<div class="d-flex flex-row ">')
print('<div class="card m-1" style="width: 28rem;">',
      '<img  src="/content/drive/MyDrive/Colab Notebooks/ex2_table/threats_bar.png" class="card-img-top" alt="...">',
      '<div class="card-body">')
    
for i in range(title.__len__()):
    print(i+1, " - ", title[i], "; ")
    i += 1
print('</div>', '</div>')
print('<div>')

"""# Полная столбчатая диаграмма + подсчёт результатов"""

# Commented out IPython magic to ensure Python compatibility.

import os
import time
from google.colab import auth
auth.authenticate_user()
!pip install --upgrade gspread

import gspread
from oauth2client.client import GoogleCredentials
print('\nРаботаем с таблицей')
# %ll -lAF /content/drive/MyDrive/"Colab Notebooks"/ex2_table/
gs = gspread.authorize(GoogleCredentials.get_application_default())
os.stat('/content/drive/MyDrive/Colab Notebooks/ex2_table/grooming1.gsheet')
table = gs.open_by_key('1vadY3Rfap6x2k2GG-_SRWftGApEWWBqyUflBOW5SejU')
print(dir(table))
worksheet = table.worksheet('results')  
rows = worksheet.get_all_values()
print(rows)
strength = [0] * 4
s = 0
opportunities = [0] * 4
o = 0
weakness = [0] * 4 
w = 0
threats = [0] * 4
t = 0
flag = 'strength'
for i in rows:
  if i[0] == 'strength':
    flag = 'strength'
  if i[0] == 'weakness':
    flag = 'weakness'
  if i[0] == 'opportunities':
    flag = 'opportunities'
  if i[0] == 'threats':
    flag = 'threats'
  if flag == 'strength' and i[4] != '' and i[4] != 'powers':
    strength[s] = i[4]
    s = s + 1
  if flag == 'opportunities' and i[4] != '' and i[4] != 'powers':
    opportunities[o] = i[4]
    o = o + 1
  if flag == 'weakness' and i[4] != '' and i[4] != 'powers':
    weakness[w] = i[4]
    w = w + 1
  if flag == 'threats' and i[4] != '' and i[4] != 'powers':
    threats[t] = i[4]
    t = t + 1
print(strength)
print(opportunities)
print(weakness)
print(threats)
streng = 0
opport = 0
weak = 0
threat = 0
for i in strength:
  streng = streng + float(i)
for i in opportunities:
  opport = opport + float(i)
for i in weakness:
  weak = weak + float(i)
for i in threats:
  threat = threat + float(i)
worksheet.update('G5', 'Подсчёт всех результатов: ' )
worksheet.update('G6', 'sum power ' + str(streng + opport - weak - threat))
worksheet.update('G7', 'probability of good result ' + str((streng+opport)/(streng+opport+weak+threat))) 
worksheet.update('G8', 'all strengths ' + str(streng))
worksheet.update('G9', 'all opportunities ' + str(opport)) 
worksheet.update('G10', 'all weaknesses ' + str(weak)) 
worksheet.update('G11', 'all threats ' + str(threat)) 
import matplotlib.pyplot as plt
x=list()
x_float=list()
title=list()
y_float=list()
    
title = [ "strengths", "weaknesses", "opportunities", "threats", "result"]
x=title
x_float = [1, 2, 3, 4, 5]
result = streng - 1*weak + opport - 1*threat
y = [streng, weak, opport, threat]
y_float = [streng, -1*weak, opport, -1*threat,  result]
print(x_float,title,y_float)
print('списки формированы-->\n')
x_pos=list()
for i in range(x_float.__len__()):
    x_pos.append(i)
print('<!--разбивка по абсцисс и значения ординат\n', len( x_float), x_pos, y_float, ' -->\n')

fig=plt.figure(figsize=(8,6), dpi=72)
plt.bar(x_pos, y_float, width=0.75, align='edge', alpha=0.4)
plt.xticks(x_pos,  x_float, fontsize=14)
plt.xlabel('Обозначения1', fontsize=14)
plt.ylabel('Мощность воздействия', fontsize=14)
plt.title('SWOT', fontsize=14)
plt.grid(True, color='r', linestyle='-', linewidth=2)
#plt.draw()
plt.show()
fig.savefig("/content/drive/MyDrive/Colab Notebooks/ex2_table/matplot_bar_swot.png")
print('<div class="d-flex flex-row ">')
print('<div class="card m-1" style="width: 28rem;">',
      '<img  src="/content/drive/MyDrive/Colab Notebooks/ex2_table/matplot_bar_swot.png" class="card-img-top" alt="...">',
      '<div class="card-body">')
    
for i in range(title.__len__()):
    print(i+1, " - ", title[i], "; ")
    i += 1
print('</div>', '</div>')
print('<div>')

