# -*- coding: utf-8 -*-
"""lambda

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UCW5ZAHKE36biHM3AoW9zN7ZxQIcp-JJ

задание 5 "лямбда"
"""

print("заполните имя, фамилию, возраст")
n = 4
xx = [0]*n
for i in range(n):
  xx[i] = input()
print("Вы заполнили следующим образом:")
print(xx)
print("сортировка по возрасту:")
print(sorted(xx, key = lambda x: int(x[-2])))
print("минимальный возраст")
print(min(xx, key = lambda x: int(x[-2])))