# -*- coding: utf-8 -*-
"""minimal4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1om2t9Ipi7aXvoukuROxzlOFs2pQ_XafX

задание1
"""

a = int(input())
b = int(input())
c = int(input())
d = int(input())
def min4(a,b,c,d):
  return min(min(min(a,b),c),d)
print("minimal number is", min4(a,b,c,d))