# -*- coding: utf-8 -*-
"""my_div

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s1O2u8jvCsGQZG7V9iel06tcMesUMzJq

задание 2 "Деление"
"""

a = int(input())

def my_div(a):
    max = 0
    for i in range(a//2, 0, -1):
        if a % i == 0:
            max = i
            break
    if max != 1:
        return max
    else:
        return a



print(my_div(a))