# -*- coding: utf-8 -*-
"""my_power

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hS96UKCiqANTQ1KAFuoBb3FO_XmMjaC0

возведение числа в степень
"""

def my_power(a,n):
  if n == 0:
    return 1
  elif n == 1:
    return a
  while n>1:
    return a*my_power(a,n-1)

a = int(input())
n = int(input())

print(my_power(a,n))