# -*- coding: utf-8 -*-
"""summa(a,b)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A9z7V5mvZIjROO4P1STNfyNUu77O9X2Z

task 3 summa
"""

a = int(input())
b = int(input())
def my_sum(a,b):
  if b == 0:
    return a
  else:
    return my_sum(a+1,b-1)
print(my_sum(a,b))