# -*- coding: utf-8 -*-
"""Ланских 25.11 range

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QI-F5PGIRh7HFZrxfiOeaGaDKGCZD4cJ

1. Вывести числа
"""

a = int(input())
b = int(input())
for i in range(a,b+1):
  print(i)

a = int(input())
b = int(input())
for i in range(a,b-1,-1):
  print(i)