# -*- coding: utf-8 -*-
"""test2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u_LoH1Z22exf0FCfzPTWk2hiOxlqP52S
"""

A = int(input())
B = int(input())
if A < B:
  for i in range(A,B+1):
    if ((i % 10) == (i // 1000)) and ((i // 10 % 10) == (i // 100 % 10)):
      print(i)
else:
  for i in range(A,B-1,-1):
    if ((i % 10) == (i // 1000)) and ((i // 10 % 10) == (i // 100 % 10)):
      print(i)